function question(){
  `
  How many direct and indirect child nodes does each parent node
  — starting with the element with an id of 1
  — have in the DOM generated by the following HTML:

  Consider the following when counting the direct and indirect child nodes for each parent node:

    Any DOM node that has at least one child node is a parent node.
    Indirect child nodes are all descendants of a node's direct children, excluding the direct children themselves.

  #1
    - 6 direct children (empty, h1, p, a, div, empty)
    - 6 indirect
  #2
    - 2 direct children (text, em)
    - 1 indirect
  #3
    - 1 direct child (text)
    - 0 indirect
  #4
    - 6 direct children (empty, text,  empty, span,  text  empty)
    - 1 indirect
  #5
    - 1 direct child (text)
    - 0 indirect
  #6
    - 1 direct child (strong)
    - 1 indirect
  #7
    - 1 direct child (text)
    - 0 indirect
  #8
    - 1 direct child (p)
    - 2 indirect
  #9
    - 1 direct child (a)
    - 1 indirect
  #10
    - 1 direct child (text)
    - 0 indirect



  `
}

<div id="1">
  <h1 id="2">Hello, <em id="3">World</em></h1>
  <p id="4">
    Welcome to wonderland. This is an
    <span id="5">awesome</span> place.
  </p>
  <a href="#" id="6"><strong id="7">Enter</strong></a>
  <div id="8"><p id="9"><a href="#" id="10">Go back</a></p></div>
</div>

function answer(){
  `
                                        div
                    empty    h1        p         a         div     empty

              h1
        text      em
                 text

                            p
        empty   text    empty   span    text  empty
                                text

                            a
                          strong
                           text

                           div
                      p            a
                                text
  `
}